apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-one
  labels:
    app: redis-one
spec:
  selector:
    matchLabels:
      app: redis-one
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-one
    spec:
      nodeSelector:
        kubernetes.io/hostname: $SENTINEL_REDIS_ONE_DEPLOYMENT_NODESELECTOR_KUBERNETES_IO_HOSTNAME
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-persistent-volume-claim
      containers:
        - name: redis
          image: $SENTINEL_REDIS_ONE_DEPLOYMENT_IMAGE
          resources:
            requests:
              cpu: $SENTINEL_REDIS_ONE_DEPLOYMENT_RESOURCES_REQUESTS_CPU
              memory: $SENTINEL_REDIS_ONE_DEPLOYMENT_RESOURCES_REQUESTS_MEMORY
          env:
            - name: MASTER_ANNOUNCE_IP
              value: !!str $SENTINEL_REDIS_ONE_DEPLOYMENT_ENV_MASTER_ANNOUNCE_IP
            - name: MASTER_ANNOUNCE_PORT
              value: !!str $SENTINEL_REDIS_ONE_DEPLOYMENT_ENV_MASTER_ANNOUNCE_PORT
            - name: SENTINEL_ANNOUNCE_PORT
              value: !!str $SENTINEL_REDIS_ONE_DEPLOYMENT_ENV_SENTINEL_ANNOUNCE_PORT
            - name: REDIS_MASTER_PASSWORD
              value: $SENTINEL_REDIS_ONE_DEPLOYMENT_ENV_REDIS_MASTER_PASSWORD
            - name: MASTER_GROUP_NAME
              value: "mymaster"
            - name: REDIS_SENTINEL_QUORUM
              value: "2"
            - name: DB_FILENAME
              value: "dump_one.rdb"
            - name: DOWN_AFTER_MILLISECONDS
              value: "10000"
            - name: FAILOVER_TIMEOUT
              value: "30000"
          ports:
            - containerPort: $SENTINEL_REDIS_ONE_DEPLOYMENT_PORTS_REDIS_MASTER_CONTAINER_PORT
              name: redis-master
            - containerPort: $SENTINEL_REDIS_ONE_DEPLOYMENT_PORTS_REDIS_SENTINEL_CONTAINER_PORT
              name: redis-sentinel
          volumeMounts:
            - name: redis-storage
              mountPath: /data
